#!/usr/bin/env bash

PATH=$PATH:/run/current-system/sw/bin

echo preparing for clash...

mkdir -p /etc/clash
chown -R clash:clash /etc/clash

# ip rule add fwmark 0x233 table 100
# ip route add local 0.0.0.0/0 dev lo table 100
# nft -f /etc/clash/scripts/clash.nft
sed -i 's/server=127.0.0.1#5353/server=127.0.0.1#5355/g' /etc/dnsmasq.conf
# systemctl restart dnsmasq
echo clash is ready to start
