# port: 7890
# socks-port: 7891
# mixed-port: 7892
# redir-port: 7893
# tproxy-port: 7894
allow-lan: true
mode: Rule
log-level: warning
external-controller: 192.168.5.1:9090
external-ui: yacd
secret: ""
ipv6: true
bind-address: '*'
cfw-latency-url: http://cp.cloudflare.com/generate_204

# interface-name: ppp0
tun:
  enable: true
  stack: mixed
  auto-route: true
  gso: false
  inet4-route-address:
    - 198.18.0.0/15
    - 8.8.8.8/32
    - 1.1.1.1/32
    - 91.108.4.0/32
    - 91.108.8.0/22
    - 91.108.12.0/22
    - 91.108.16.0/22
    - 91.108.20.0/22
    - 91.108.56.0/22
    - 91.108.192.0/22
    - 149.154.160.0/20
    - 185.76.151.0/24
  inet6-route-address:
    - fc00::/18
    - 2001:b28:f23d::/48
    - 2001:b28:f23f::/48
    - 2001:67c:4e8::/48
    - 2001:b28:f23c::/48
    - 2a0a:f280::/32

dns:
  enable: true
  ipv6: true
  listen: :5355
  enhanced-mode: fake-ip
  default-nameserver:
    - 223.5.5.5
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - tls://dns.google:853
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
rules:
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
  - MATCH,Proxy
