port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
allow-lan: true
mode: Rule
log-level: warning
external-controller: 192.168.5.1:9090
external-ui: yacd
secret: ""
ipv6: true
bind-address: '*'
cfw-latency-url: http://cp.cloudflare.com/generate_204
dns:
  enable: true
  ipv6: true
  listen: :5355
  enhanced-mode: fake-ip
  default-nameserver:
    - 223.5.5.5
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - tls://dns.google:853
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
rules:
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
  - MATCH,Proxy
